### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by eunjjungg** [AndroidStudy00-s/Android#1]
## 📑 Topic
MVC - W1

##  🤔Question
- eunjjungg 문제 : MVC에서 유저의 이벤트를 받는 부분은 View이다 (O, X)
- eunjjungg 문제 : Android의 MVC에서 Controller도 모듈화와 테스트가 용이하다 (O, X)

- jiwon2724 문제 : Model에선 비즈니스 로직을 담당하지 않는다! (O, X)
- jiwon2724 문제 : 안드로이드에서 MVC패턴을 설계할 때 쉬운이유를 설명해주세요!

- lhb8106 문제 : MVC 패턴에서는 View와 Model 사이의 의존성이 높다 ( O / X )
- lhb8106 문제 : MVC 패턴의 장,단점에 대해서 설명해주세요 !

**Comment by eunjjungg** [comment]
- jiwon2724 문제 : Model에선 비즈니스 로직을 담당하지 않는다! (O, X)
   + X
- jiwon2724 문제 : 안드로이드에서 MVC패턴을 설계할 때 쉬운이유를 설명해주세요!
   + Model을 분리한다고 해도 View, Controller가 Activity, Fragment에서 다 작성이 가능하기 때문에 간단한 앱을 설계할 때는 한 클래스에 밀어넣으면 돼서 쉽습니다.

**Comment by jiwon2724** [comment]
- lhb8106 문제 : MVC 패턴에서는 View와 Model 사이의 의존성이 높다 ( O / X )
   - 맞습니다! MVC 패턴에서 View와 Controller는 Activity, Fragment이므로 Model을 해당 컴포넌트 안에서 호출해야합니다.



- lhb8106 문제 : MVC 패턴의 장,단점에 대해서 설명해주세요 !
   - 장점
      - 빠르고 간단하게 구현이 가능하다.
   - 단점
     - View와 Model간 의존성이 높다.
     - 앱이 커질수록 코드 라인과 복잡도가 증가한다.
     - 요소들이 분리가 되어있지 않아 유지보수가 어렵다.

**Comment by lhb8106** [comment]
- eunjjungg 문제 : MVC에서 유저의 이벤트를 받는 부분은 View이다 (O, X)
   - O. View에서 사용자의 이벤트를 받아들이고 이를 Controller에 전달합니다. 정확히는 Activity (View, Controller)가 사용자 이벤트를 감지합니다. 

- eunjjungg 문제 : Android의 MVC에서 Controller도 모듈화와 테스트가 용이하다 (O, X)
   - X. 무듈화 및 유연성의 한계가 있으며 테스트 용이성이 떨어집니다. 따라서 유닛테스트 또한 어렵습니다.
