### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by jiwon2724** [AndroidStudy00-s/Android#2]
## 📑 Topic
MVP - W1

##  🤔Question
- jiwon2724 문제 : `Presenter`와 `View`는 1:1 관계인가요? (O, X)
- eunjjungg 문제 : MVC 패턴에 비해 `Model` <-> `View`의 결합도는 여전하지만 `View` <-> `Presenter`의 결합도는 줄었다 (O, X)
- eunjjungg 문제 : UI 갱신이 필요할 때 흐름이 어떻게 되나요? (M, V, P 중 어느 방향으로 흐르는지)
- lhb8106 문제 : MVC 패턴에서의 `Controller`와 MVP 패턴에서의 `Presenter`의 차이점을 설명해주세요 !

**Comment by eunjjungg** [comment]
- jiwon2724 문제 : Presenter와 View는 1:1 관계인가요? (O, X)
   - 넹

**Comment by jiwon2724** [comment]
- lhb8106 문제 : MVC 패턴에서의 Controller와 MVP 패턴에서의 Presenter의 차이점을 설명해주세요 !
   - 기존 Controller는 View와 Model간 의존성이 있었지만, MVP 패턴에선 Presenter를 도입 하여 의존성을 해결함. Presenter에서 Model을 호출한다.

**Comment by lhb8106** [comment]
- eunjjungg 문제 : MVC 패턴에 비해 Model <-> View의 결합도는 여전하지만 View <-> Presenter의 결합도는 줄었다 (O, X)
   - X. Model과 View 사이의 결합도는 낮아지지만, View와 Presenter 사이의 결합도는 높아집니다.
   
- eunjjungg 문제 : UI 갱신이 필요할 때 흐름이 어떻게 되나요? (M, V, P 중 어느 방향으로 흐르는지)
   - View에서 user action이 일어납니다. -> Presenter로 해당 action이 전달됩니다. -> Presenter에서 로직을 처리합니다. -> Model로의 접근이 필요한 경우 수행합니다. -> Presenter에 View 업데이트를 요청합니다 -> View가 갱신됩니다.
