### ISSUE TITLE
MVVM

### ISSUE THREAD

**Issue by jiwon2724** [AndroidStudy00-s/Android#3]
## 📑 Topic
MVVM - W1

##  🤔Question
- jiwon2724 문제 : AAC ViewModel과 ViewModel은 어떻게 다른가요!?
- eunjjungg 문제 : MVP의 Presenter와 MVVM의 ViewModel의 공통점, 차이점 각각 하나씩 알려주세요!
- lhb8106 문제 : MVVM에서의 ViewModel은 View와 1:1 관계를 이룹니다. (o/x)
- lhb8106 문제 : MVVM의 장단점에 대해 설명해주세요 !

**Comment by eunjjungg** [comment]
- jiwon2724 문제 : AAC ViewModel과 ViewModel은 어떻게 다른가요!?
   - 엄밀히 말하면 AAC ViewModel**만** 사용하면 MVVM의 ViewModel을 구현할 수 없습니다. 왜냐하면 View-Model 사이의 데이터 바인딩 기능이 없기 때문입니다. AAC ViewModel은 그것보다는 Activity/Fragment가 onDestroy() 될 때 해제해주는 역할을 하게 됩니다. 하지만 AAC ViewModel을 사용해서 MVVM ViewModel을 구현할 수는 있습니다.  + 생명주기도 알고 있기 때문에~!

**Comment by jiwon2724** [comment]
- lhb8106 문제 :  MVVM에서의 ViewModel은 View와 1:1 관계를 이룹니다. (o/x)
   - X!! 1:N 관계입니다.
- lhb8106 문제 : MVVM의 장단점에 대해 설명해주세요 !
   - 장점 
      - View와 Model간 의존성이 없다.
      - View와 ViewModel이 바인딩되어 코드의 양이 줄어든다.
      - 데이터의 갱신을 자동으로 받을 수 있다.
   - 단점
      - 설계가 어렵고 복잡하다.
      - Observe 기술에 대한 이해도가 필요하다.

**Comment by lhb8106** [comment]
- eunjjungg 문제 : MVP의 Presenter와 MVVM의 ViewModel의 공통점, 차이점 각각 하나씩 알려주세요!
   - 공통점 : Model과 View사이의 의존성이 없습니다
   - 차이점: MVP의 경우 View과 Presenter의 결합도는 여전히 높았지만, MVVM에서는 View와 ViewModel사이의 의존성이 없기때문에 테스트에 용이합니다.
