### ISSUE TITLE
4대 컴포넌트

### ISSUE THREAD

**Issue by jiwon2724** [AndroidStudy00-s/Android#4]
## 📑 Topic
4대 컴포넌트 - W1

##  🤔Question
- jiwon2724 문제 : 프로필 사진을 업데이트하려고 합니다. 갤러리 앱을 들어가기 위해선 어떻게 해야 할까요!?
- lhb8106 문제 : 액티비티와 서비스는 UI 스레드라고 불리는 동일한 애플리케이션 스레드로 실행됩니다. ( O / X )
- lhb8106 문제 : 백그라운드 서비스에서 음악 재생과 데이터 동기화처리에 대한 차이점을 설명해주세요 !
- eunjjungg 문제 : 구성 요소 유형 네 가지 중 세 가지(액티비티, Content Provider, Broadcast Receiver)는 인텐트라는 비동기식 메시지로 활성화됩니다 ( O / X )

**Comment by jiwon2724** [comment]
- lhb8106 문제 : 액티비티와 서비스는 UI 스레드라고 불리는 동일한 애플리케이션 스레드로 실행됩니다. ( O / X )
   - 동일한 스레드에서 실행됩니다. 그러나 서비스는 메인 스레드에서 동작하지만, 서비스의 스레드는 별도의 스레드에서 동작합니다!
- lhb8106 문제 : 백그라운드 서비스에서 음악 재생과 데이터 동기화처리에 대한 차이점을 설명해주세요 !
    - 음악 재생 : 사용자가 바로 인식할 수 있게 해야하는 처리는 프로세스가 계속 실행되도록 해야한다.
    - 데이터 동기화 : 사용자가 실행되는 작업을 인식할 수 없는 경우는 자유롭게 프로세스를 관리할 수 있다. 사용자가 더 필요한 작업에 RAM이 필요한경우 해당 서비스를 종료할 수 있다.

**Comment by eunjjungg** [comment]
+ jiwon2724 문제 : 프로필 사진을 업데이트하려고 합니다. 갤러리 앱을 들어가기 위해선 어떻게 해야 할까요!?
   + 프로필 사진이 있는 앱에서 ContentResolver 객체를 사용해서 데이터를 요청하면 갤러리 앱으로부터 요청된 작업을 수행하고 데이터를 원래 앱으로 받아야 합니다. 내부적으로는 ContentResolver가 ContentProvider 객체와 통신하고 ContentProvider가 데이터 요청을 하게 됩니다. 
   + 땡일지도 모름!!!!!!!!!!!!!!!!!!! ContentProvider 방식도 있고 Intent 방식도 있다

**Comment by lhb8106** [comment]
- eunjjungg 문제 : 구성 요소 유형 네 가지 중 세 가지(액티비티, Content Provider, Broadcast Receiver)는 인텐트라는 비동기식 메시지로 활성화됩니다 ( O / X )
   + X. 세 가지가 액티비티, 서비스, Broadcast Receiver입니다.
