### ISSUE TITLE
MVI

### ISSUE THREAD

**Issue by lhb8106** [AndroidStudy00-s/Android#5]
## 📑 Topic
MVI - W1

##  🤔Question
- lhb8106 문제 : MVI에서의 Intent와 안드로이드의 메시징 객체인 Intent는 같다 ( O / X )
- lhb8106 문제 : MVVM에서 해결하지 못하는 문제와 이를 해결한 MVI의 특징에 대해 설명해주세요 !
- jiwon2724 문제 : MVI의 Model은 상태를 표현하는 데이터이다!? ( O / X )
- eunjjungg 문제 : MVI에서 Model은 원칙적으로는 객체 내부 데이터를 수정할 수 없지만 새로운 상태를 만드는 일부 경우에는 내부 데이터 수정을 허용한다. (O / X) 
- eunjjungg 문제 : MVI 패턴에서 user는 직접 뷰를 건드려 model의 변화를 야기시킬 수 있다. (O / X)

**Comment by eunjjungg** [comment]
- jiwon2724 문제 : MVI의 Model은 상태를 표현하는 데이터이다!? ( O / X )
   - Ye a h..!

**Comment by jiwon2724** [comment]
- lhb8106 문제 : MVI에서의 Intent와 안드로이드의 메시징 객체인 Intent는 같다 ( O / X ) 
   - 아닙니다! Intent는 유저의 Action을 받습니다.
- lhb8106 문제 : MVVM에서 해결하지 못하는 문제와 이를 해결한 MVI의 특징에 대해 설명해주세요 
   - 상태 문제와 부수효과를 해결하기위해 UDF를 사용하고, 부수효과(Side Effects)를 Intent에서 설정해줘서 해결.
   - pure cycle과 side effect cycle을 따로 관리하여 해결한다.

**Comment by lhb8106** [comment]
eunjjungg 문제 : MVI에서 Model은 원칙적으로는 객체 내부 데이터를 수정할 수 없지만 새로운 상태를 만드는 일부 경우에는 내부 데이터 수정을 허용한다. (O / X)
   - O...? 
   - 땡 !!!!!! X!!!!!!!!! 기존 내부 데이터를 수정하는 것이 아니라 새로운 것을 만드는 것임!


eunjjungg 문제 : MVI 패턴에서 user는 직접 뷰를 건드려 model의 변화를 야기시킬 수 있다. (O / X)
   - X...? 사용자의 액션을 나타내는 intent를 통해 간접적으로 모델의 상태를 변경시키기 때문..!

**Comment by eunjjungg** [comment]
val a = Person("ej", 3)
val b = a.copy()
