### ISSUE TITLE
코루틴(Coroutine)

### ISSUE THREAD

**Issue by jiwon2724** [AndroidStudy00-s/Android#6]
## 📑 Topic
코루틴(Coroutines) - W2

##  🤔Question
- jiwon2724 문제 : `launch`와 `async`의 차이점을 설명해주세요!
- jiwon2724 문제 : `await()` 함수를 만났을 때 일어나는일을 설명해주시고, result의 결과값을 알려주세요!
```kotlin
runBlocikg {
    val value1 = async { getRandom1() }
    val value2 = async { getRandom2() }
    val reusult = value1.await() + value2.await()
}

fun getRandom1(): Int = Random.nextInt(100)
fun getRandom2(): Int = Random.nextInt(100)

```

- lhb8106 문제 : 코루틴의 세가지 디스패처에 대해 설명해주세요 !
- lhb8106 문제 : withContext()에 대해 아는만큼 설명해주세요 !
- eunjjungg 문제 : 네트워크 관련 작업을 메인 스레드에서 실행하려고 합니다. 이때의 문제점과 해결 방안을 알려주세요.
- eunjjungg 문제 : 아래 코드의 출력 결과를 예측해주세요. 

```kotlin
suspend fun main() { 
    get() 
    print("main last line") 
}

suspend fun get() { 
    withContext(Dispatchers.IO) { 
        delay(2000L) 
        println("withContext") 
    }
    println("get last line") 
}
```

**Comment by jiwon2724** [comment]
- lhb8106 문제 : 코루틴의 세가지 디스패처에 대해 설명해주세요 !
정답 : 
Main : UI 스레드에서 코루틴을 실행 -> UI와 상호작용한다. 서버에서 가져온 데이터 View에 매핑.
Default : CPU를 많이 사용하는 작업.(JSON 파싱, 리스트 정렬 등) UI 스레드 외부에서 실행되도록 최적화 되어있다. 
IO : UI 스레드 외부에서 디스크, 파일, 네트워크 I/O를 실행하는데 최적화 되어있다.

- lhb8106 문제 : withContext()에 대해 아는만큼 설명해주세요 !
정답 : withContext를 사용하여 코루틴 컨텍스트(Dispatchers.XX)를 변경해준다. 즉, 파라미터로 들어온 코루틴 컨텍스트를 사용하여 블럭 안에 있는 로직 수행이 끝날 때 까지 일시중단 한 다음 결과를 반환한다. 반환 후 원래 디스패처로 돌아간다.

**Comment by eunjjungg** [comment]
+ jiwon2724 문제 : launch와 async의 차이점을 설명해주세요!
  + launch는 새 코루틴을 시작하고 호출자에게 결과를 반환하지 않지만 async는 새 코루틴을 시작하고 await이라는 정지 함수로 결과를 반환하도록 함. 무엇보다 launch는 job을 반환하고 async는 deffered를 반환함. 
+ jiwon2724 문제 : await() 함수를 만났을 때 일어나는일을 설명해주시고, result의 결과값을 알려주세요!
``` kotlin
runBlocikg {
    val value1 = async { getRandom1() }
    val value2 = async { getRandom2() }
    val reusult = value1.await() + value2.await()
}

fun getRandom1(): Int = Random.nextInt(100)
fun getRandom2(): Int = Random.nextInt(100)
```
   + async로 시작한 코루틴의 값이 반환될 때까지 기다림. 그리고 값은.. 0..99*2 사이의 값이 나오게 됩니다..

**Comment by lhb8106** [comment]
- eunjjungg 문제 : 네트워크 관련 작업을 메인 스레드에서 실행하려고 합니다. 이때의 문제점과 해결 방안을 알려주세요.
   - ANR이 발생할 수 있음. 따라서 백그라운드에서 네트워크 관련 작업을 하도록 요청해야함!


- eunjjungg 문제 : 아래 코드의 출력 결과를 예측해주세요. 

```kotlin
suspend fun main() { 
    get() 
    print("main last line") 
}

suspend fun get() { 
    withContext(Dispatchers.IO) { 
        delay(2000L) 
        println("withContext") 
    }
    println("get last line") 
}
```
   - withContext
get last line
main last line
