### ISSUE TITLE
생명주기(Lifecycle)

### ISSUE THREAD

**Issue by jiwon2724** [AndroidStudy00-s/Android#7]
## 📑 Topic
생명주기(Lifecycle) - W2

##  🤔Question
- jiwon2724 문제 : 
시나리오 : FirstActivity에서 버튼을 클릭하면 SecondActivity로 이동한다. 이동이 완료된 후 SecondActivity에서 finish()를 호출하여 다시 FirstActivity이동 됐다. 해당 시나리오의 생명주기를 설명해주세요!

- jiwon2724 **억까**문제 : 
![image](https://github.com/AndroidStudy00-s/Android/assets/70135188/93f7e00d-772f-41a1-aabd-3d9e2e64ea71)
Activity에 다음과 같은 화면이 있습니다. 이는 유저가 `Dialog`를 커스텀하여 만든 요소입니다. 버튼을 클릭하면 해당 다이얼로그가 화면에 보여지는데, 이 때 생명주기의 상태는 무엇일까요!?

- jiwon2724 문제 : Fragment 생명주기중 onDestroy()는 UI요소가 제거될 때 호출된다. (O, X)

- lhb8106 문제 : `onPause()` 상태에서 사용자의 데이터를 저장하거나, 네트워크 호출을 하거나, 데이터베이스 트랜잭션 등을 수행하기에 적합합니다. (O , X)
- lhb8106 문제 : 앱은 항상 백그라운드에서 실행될 때 활동을 실행할 수 없습니다. (O, X)
- lhb8106 문제 : Fragment의 `onViewCreated()`에서 사용할 수 있는 적절한 기능에는 무엇이 있을까요?

- eunjjungg 문제 : 부하가 큰 할당 해제 작업을 액티비티가 종료되려 할 때 작업하려고 합니다. 어느 콜백에서 해제해주는 것이 맞을까요?
- eunjjungg 문제 : 기기 회전이 발생했을 때 액티비티의 라이프 사이클을 알려주세요.
- eunjjungg 문제 : fragment가 혜빈에게 보여지고 있습니다. 하지만 다음 화면이 보고 싶어 넘기려고 합니다. 화면이 넘어가는 애니메이션이 보이고 있습니다. 이때의 fragment의 lifecycle 중 콜백은 어떤 것이 호출되나요?

**Comment by jiwon2724** [comment]
- lhb8106 문제 : 앱은 항상 백그라운드에서 실행될 때 활동을 실행할 수 없습니다. (O, X)
정답 : X `onPause()`는 아주 잠깐 실행된다! 시간이 걸리는 작업 등은 적절하지 않다. 
- lhb8106 문제 : 앱은 항상 백그라운드에서 실행될 때 활동을 실행할 수 없습니다. (O, X)
정답 : X..? 앱이 백그라운드인 경우엔 `onStop()`인 상태인데, 다시 앱으로 들어가지 않는 이상 재개됨 상태로 들어갈 수 없을 것 같음!
- lhb8106 문제 : Fragment의 onViewCreated()에서 사용할 수 있는 적절한 기능에는 무엇이 있을까요?
정답 : View의 초기값을 설정해주거나, 어댑터 세팅, LiveData 옵저빙 작업을 해주는게 적절하다. `onCreateView()`에서 Fragment의 레이아웃 루트가 그려지면 호출되는 콜백 메서드가 `onViewCraeted()`여서, UI가 그려졌음을 보장한다.

**Comment by eunjjungg** [comment]
+ jiwon2724 문제 :
시나리오 : FirstActivity에서 버튼을 클릭하면 SecondActivity로 이동한다. 이동이 완료된 후 SecondActivity에서 finish()를 호출하여 다시 FirstActivity이동 됐다. 해당 시나리오의 생명주기를 설명해주세요!
   + _onCreated(1) -> onStart(1) -> onResume(1) -> onPause(1) -> onCreate(2) -> onStart(2) -> onStop(1) -> onResume(2) -> onPause(2) -> onStop(2) -> onDestroy(2) -> onRestart(1) -> onStart(1) -> onResume(1)가 됩니다._ **틀림**
   
정답 : onCreate(1) -> onStart(1) -> onResume(1) -> 버튼 클릭! -> onPause(1) -> onCreate(2) -> onStart(2) -> onResume(2) -> onStop(1) -> finish()호출! -> onPause(2) -> onRestart(1) -> onStart(1) -> onResumse(1) -> onStop(2) -> onDestroy(2)

화면 전환시 onPause 상태에서 보여지 화면이 다 렌더링된 후에 이전 화면이 onStop이 된다.





+ jiwon2724 억까문제 :
   + _onPause()가 호출되는 즉 pause 상태입니다!_ **틀림**
   + resume 상태임.

정답 : 권한요청 다이얼로그 같은 경우엔 onPause()가 호출이 되지만, 유저가 Dialog를 사용해서 띄어주는 경우엔 onPause()가 실행되지 않음. 권한요청은 Activity로 실행된다 (아마 다이얼로그 처럼 커스텀 한듯.)
참고자료 : https://programmar.tistory.com/46

+ jiwon2724 문제 : Fragment 생명주기중 onDestroy()는 UI요소가 제거될 때 호출된다. (O, X)
   + X, onDestroyView()입니다.

**Comment by lhb8106** [comment]
- eunjjungg 문제 : 부하가 큰 할당 해제 작업을 액티비티가 종료되려 할 때 작업하려고 합니다. 어느 콜백에서 해제해주는 것이 맞을까요?
   +  onStop() ! 

- eunjjungg 문제 : 기기 회전이 발생했을 때 액티비티의 라이프 사이클을 알려주세요.
   + onResume()까지 호출 된 액티비티에서 화면 회전이 발생하면 onPause() -> onStop() -> onDestroy()까지 호출되어 종료 된 후, 다시 onCreate() -> onStart() -> onResume()까지 호출됩니다!

- eunjjungg 문제 : fragment가 혜빈에게 보여지고 있습니다. 하지만 다음 화면이 보고 싶어 넘기려고 합니다. 화면이 넘어가는 애니메이션이 보이고 있습니다. 이때의 fragment의 lifecycle 중 콜백은 어떤 것이 호출되나요?
   + onPause() ..? 유저가 프래그먼트를 떠난다는 신호이므로..? 그리고 화면이 보이지 않으면 onStop(), 애니메이션이 완료되면 onDestroyView()로 넘어가니까..?
