### ISSUE TITLE
페이징(Paging)

### ISSUE THREAD

**Issue by lhb8106** [AndroidStudy00-s/Android#8]
## 📑 Topic
페이징(Paging) - W3

##  🤔Question
- lhb8106 문제 : Paging의 각 레이어에 대해 설명해주세요!
- lhb8106 문제 : PagingData는 해당 레이어를 UI와 연결하는 역할을 수행하지 않습니다 (O/X)
- lhb8106 문제 : PagingDataAdapter를 사용하지 않고 PagingAdapter를 구현할 수 있을까요? 있다면 어떤 방법으로 구현해야하며, 불가능하다면 그 이유가 뭔지 설명해주세요!
- jiwon2724 문제 : Paging3를 통해서 무한 스크롤을 구성할 때 실행되는 플로우를 설명해주세요! (api call)
- eunjjungg 문제 : loadstate adapter를 직접 만들어서 PagingAdapter 클래스의 인스턴스에 연결해줄 때 아래와 같이 사용하면 된다. (O, X)
```
var adapter = GroupListAdapter()
adapter.withLoadStateAdapters(
    header = GroupListLoadStateAdapter { adapter.retry() },
    footer = GroupListLoadStateAdapter { adapter.retry() }
)
binding.rvGroupList.adapter = adapter
```
- eunjjungg 문제 : PagingSource에서 아직 페이징이 한 번도 실행되지 않아 첫 번째 페이지 값을 정할 때 [0, 100] 중의 숫자 중에 무엇을 기준으로 정하면 좋을까요?
- eunjjungg 문제 : PagingSource에서 params.loadSize 기준으로 api 또는 내부 DB로부터 로드가 될텐데 첫 번째 로드일때는 별다른  설정을 해주지 않는다면 배수로 뽑히게 된다. (O, X)

**Comment by jiwon2724** [comment]
- lhb8106 문제 : Paging의 각 레이어에 대해 설명해주세요!
정답 : 
Repository : 페이징 라이브러리 구성요소를 구현한다. 데이터(restapi, local db)를 검색하는 방법을 정의합니다.
ViewModel : PagingConfig를 구성하여 Pager를 구현합니다. PagingSource에서 페이징된 데이터 스트림을 설정합니다.
UI : ViewModel에서 구현한 Pager를 참조하고, PagingDataAdapter를 구현합니다.


- lhb8106 문제 : PagingData는 해당 레이어를 UI와 연결하는 역할을 수행하지 않습니다 (O/X)
정답 : O! ViewModel에서 구현한 Pager를 통해 UI와 연결합니다. 

- lhb8106 문제 : PagingDataAdapter를 사용하지 않고 PagingAdapter를 구현할 수 있을까요? 있다면 어떤 방법으로 구현해야하며, 불가능하다면 그 이유가 뭔지 설명해주세요!
정답 : 가능! ListAdapter를 사용해서 구현해야 할 것 같습니다. 다만 페이징 라이브러리를 사용하지 않아 RecyclerView 스크롤 콜백을 감지하여 하단에 포지션이 잡혔을 때, PagingSource의 페이징 되는 api를 호출하여 실행해야 할 것 같음!

**Comment by eunjjungg** [comment]
+ jiwon2724 문제 : Paging3를 통해서 무한 스크롤을 구성할 때 실행되는 플로우를 설명해주세요! (api call)
   - vm에서 api call을 하여 PagingDataStream에 정의해놓은 값에 따라 pagingData 로드 -> ui에서 그 데이터를 PagingDataAdapter에 전달 -> PagingSource에서 다음 페이지를 로드하기 위해 nextKey를 봤을 때 null이면 로드를 멈추고 아니라면 페이지 로드 과정 반복

**Comment by lhb8106** [comment]
+ X
+ eunjjungg 문제 : PagingSource에서 아직 페이징이 한 번도 실행되지 않아 첫 번째 페이지 값을 정할 때 [0, 100] 중의 숫자 중에 무엇을 기준으로 정하면 좋을까요?
   -  load()의 parameter인 LoadParams는 로드 작업이 수행되는 것에 대한 정보(로딩되는데 필요한 키와 로드 아이템의 개수)를 기준으로 정한다..! (이게 원하는 답인지 몰겠숨 ;_; )
+ eunjjungg 문제 : PagingSource에서 params.loadSize 기준으로 api 또는 내부 DB로부터 로드가 될텐데 첫 번째 로드일때는 별다른 설정을 해주지 않는다면 배수로 뽑히게 된다. (O, X)
   - O...~?! initialLoadSize를 따로 정해주지 않는다면 pageSize의 배수로 뽑히게 됨.
